apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitchat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chitchat
  template:
    metadata:
      labels:
        app: chitchat
    spec:
      containers:
      - image: $dockerhuburl:$BUILD_NUMBER
        name: nodejs
        ports:
        - containerPort: 4141
---
apiVersion: v1
kind: Service
metadata:
  name: chitchat-service
spec:
  type: LoadBalancer
  selector:
    app: chitchat
  ports:
  - port: 8080
    targetPort: 4141
    protocol: TCP
